
server:
  port: 7777
spring:
  application:
    name: boot-redis-demo
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.7.122:3306/student?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1800000
#    sentinel:
#      nodes:  192.168.7.167:26379
#      master: mymaster
    host: 192.168.7.167
    port: 6379
    lettuce:

      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml

