server:
  port: 8003
spring:
  devtools:
      restart:
          enabled: true
  application:
    name: cloud-provider-payment
  datasource:
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
#    minPoolSize: 2
#    maxPoolSize: 10
#    maxIdleTime: 1800000
#    acquireIncrement: 3
#    maxStatements: 1000
#    initialPoolSize: 3
#    idleConnectionTestPeriod: 60
#    acquireRetryAttempts: 30
#    acquireRetryDelay: 1000
#    breakAfterAcquireFailure: false
#    testConnectionOnCheckout: false
    username: root
    password: lizhen123
    url: jdbc:mysql://192.168.7.77:3306/school_db?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapper/*.xml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: payment8003
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


