server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7002
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: eureka7002.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false