server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        prefer-ip-address: true
        deregister: true
        health-check-critical-timeout: 1s
        health-check-interval: 1s
        service-name: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: gateway-service1
          uri: lb://cloud-consul-payment
          predicates:
          - Path=/ddds,/xxxs



